name: td_logger
description: Small, easy to use and extensible logger for Flutter (Only in debug mode).
version: 1.0.1
homepage: https://github.com/thongdn-it/TD-Logger/tree/master
repository: https://github.com/thongdn-it/TD-Logger/tree/master

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
